name: PHP Composer

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deployment
      run: |
          cd /home/backend-superapps/htdocs/backend-superapps.newus.id
          git checkout -f
          git pull
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    - name: Install dependencies
      env:
        COMPOSER_ALLOW_SUPERUSER: 1
      run: |
        set -e
        composer install || composer update
    - run : |
          cd /home/backend-superapps/htdocs/backend-superapps.newus.id
          yes | php artisan migrate
    - run : systemctl restart nginx
