name: PHP Composer

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deployment
      run: |
          cd /home/backend-superapps/htdocs/backend-superapps.newus.id
          git checkout -f
          git pull
    - name: Install dependencies
      env:
        COMPOSER_ALLOW_SUPERUSER: 1
      run: |
        rm -rf vendor
        composer install
    - run : |
          cd /home/backend-superapps/htdocs/backend-superapps.newus.id
          yes | php artisan migrate
    - run : systemctl restart nginx
